version: 2

models:
  - name: stg_local_bike__customers
    description: "This model contains customer information including complete contact details and postal address"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name."
        tests:
          - not_null
      - name: last_name
        description: "Customer's last name."
        tests:
          - not_null
      - name: email
        description: "Customer's email address."
        tests:
          - not_null
      - name: phone
        description: "Customer's phone number."
      - name: street
        description: "Street address of the customer."
      - name: city
        description: "City where the customer resides."
      - name: state
        description: "State where the customer resides."
      - name: zip_code
        description: "ZIP code of the customer's address."

  - name: stg_local_bike__orders
    description: "This model contains information about orders placed by customers, including status and relevant dates (order, required, shipped)"
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key linking the order to the customer who placed it."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__customers')
              field: customer_id
      - name: order_status
        description: "The current status of the order (1=Pending, 2=Processing, 3=Rejected, 4=Completed)."
        tests:
          - not_null
      - name: order_date
        description: "Date when the order was placed."
        tests:
          - not_null
      - name: required_date
        description: "Date by which the customer requires the order."
        tests:
          - not_null
      - name: shipped_date
        description: "Date when the order was shipped (can be null if not yet shipped)."
      - name: store_id
        description: "Foreign key linking the order to the store where it was placed."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: staff_id
        description: "Foreign key linking the order to the staff member who processed it."
        tests:
          - relationships:
              to: ref('stg_local_bike__staffs')
              field: staff_id

  - name: stg_local_bike__order_items
    description: "This model contains details of each item included in an order, with quantities, catalog prices, and applied discounts"
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item: generated by concatenating order_id and item_id."
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__orders')
              field: order_id
      - name: item_id
        description: "Sequential number of the item within the order."
        tests:
          - not_null
      - name: product_id
        description: "Foreign key linking the order item to the product."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__products')
              field: product_id
      - name: quantity
        description: "Quantity of the product ordered."
        tests:
          - not_null
      - name: list_price
        description: "Catalog price of the product at the time of order."
        tests:
          - not_null
      - name: discount
        description: "Discount percentage applied to the product (0.0 to 1.0)."
        tests:
          - not_null
      - name: total_item_amount
        description: "Total amount for this order item, calculated as (list_price * quantity * (1 - discount))."

  - name: stg_local_bike__products
    description: "This model contains the product catalog with name, brand, category, model year, and selling price"
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product."
        tests:
          - not_null
      - name: brand_id
        description: "Foreign key linking the product to its brand."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product to its category."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__categories')
              field: category_id
      - name: model_year
        description: "Year of the product model."
        tests:
          - not_null
      - name: list_price
        description: "Selling price of the product."
        tests:
          - not_null

  - name: stg_local_bike__brands
    description: "This model contains the list of product brands sold"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
          - unique
          - not_null
      - name: brand_name
        description: "Name of the brand."
        tests:
          - not_null

  - name: stg_local_bike__categories
    description: "This model contains the list of product categories for item classification"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
          - unique
          - not_null
      - name: category_name
        description: "Name of the category."
        tests:
          - not_null

  - name: stg_local_bike__stores
    description: "This model contains store information with complete contact details (name, phone, email, address)"
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
          - unique
          - not_null
      - name: store_name
        description: "Name of the store."
        tests:
          - not_null
      - name: phone
        description: "Store's phone number."
      - name: email
        description: "Store's email address."
      - name: street
        description: "Street address of the store."
      - name: city
        description: "City where the store is located."
      - name: state
        description: "State where the store is located."
      - name: zip_code
        description: "ZIP code of the store's address (stored as STRING to preserve leading zeros)."

  - name: stg_local_bike__staffs
    description: "This model contains store employee information including personal details, active status, store assignment, and managerial hierarchy"
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff member."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Staff member's first name."
        tests:
          - not_null
      - name: last_name
        description: "Staff member's last name."
        tests:
          - not_null
      - name: email
        description: "Staff member's email address."
        tests:
          - not_null
      - name: phone
        description: "Staff member's phone number."
      - name: active
        description: "Status indicating if the staff member is currently active (1=active, 0=inactive)."
        tests:
          - not_null
      - name: store_id
        description: "Foreign key linking the staff member to their assigned store."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: manager_id
        description: "Foreign key linking the staff member to their manager (self-referencing relationship, can be null for top-level managers)."
        tests:
          - relationships:
              to: ref('stg_local_bike__staffs')
              field: staff_id
              config:
                severity: warn  # Avertissement au lieu d'erreur

  - name: stg_local_bike__stocks
    description: "This model contains real-time inventory indicating the available quantity of each product per store"
    columns:
      - name: stock_id
        description: "Primary key, unique identifier for each stock record: generated by concatenating store_id and product_id."
        tests:
          - unique
          - not_null
      - name: store_id
        description: "Foreign key linking the stock to the store."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: product_id
        description: "Foreign key linking the stock to the product."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__products')
              field: product_id
      - name: quantity
        description: "Available quantity of the product in the store."
        tests:
          - not_null